[package]
name = "lab_tasks_types"
version = "0.1.0"
edition = "2021"

[lib]
name = "lab_tasks_types"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
chrono = "0.4.39"
